server/forms/shop_forms.py
from wtforms import StringField, SubmitField, DecimalField, MultipleFileField
from flask_ckeditor import CKEditorField
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, Length, NumberRange

class ShopItemForm(FlaskForm):
    """
    Form for creating or updating shop items.
    """
    name = StringField('Name:', name="name", validators=[DataRequired(), Length(max=100)])
    description = CKEditorField('Description:', name="description", validators=[DataRequired()])
    images = MultipleFileField("Images:")
    price = DecimalField('Price:', name="price", validators=[DataRequired(), NumberRange(min=0.010, message="Price must be a positive number")], places=2, rounding=None)
    submit = SubmitField('Submit')

server/blueprints/shop.py
from flask import Blueprint, render_template, flash, redirect, url_for, current_app
from db_schema import Admin, ShopItem, db, Image
from flask_login import login_required, current_user
from server.forms.shop_forms import ShopItemForm
from werkzeug.utils import secure_filename

shop_bp = Blueprint('shop', __name__, template_folder='templates/shop')

@shop_bp.route('/')
def shop():
    items = ShopItem.query.order_by(ShopItem.name.asc()).all()
    return render_template('shop/shop.html', items=items)  # , items=items

@shop_bp.route('/<int:item_id>')
def shop_item(item_id):
    item = ShopItem.query.get_or_404(item_id)
    return render_template('shop/shop_item.html', item=item)

@shop_bp.route('/create', methods=['GET', 'POST'])
@login_required
def create_shop_item():
    """
    GET: Displays the form to create a new shop item.
    POST: Handles the creation of a new shop item.
    """
    if not current_user.is_authenticated:
        flash("You do not have permission to create shop items.", "danger")
        return redirect(url_for('shop.shop'))

    form = ShopItemForm()

    if form.validate_on_submit():
        name = form.name.data
        images = []
        for f in form.images.data:
            if f:
                filename = secure_filename(f.filename)
                f.save(f"{current_app.config['UPLOAD_FOLDER']}/{filename}")
                image = Image(filename=filename)
                db.session.add(image)
                images.append(image)

        description = form.description.data  # We don't clean as we trust the admins to not XSS their own users.
        price = form.price.data

        new_item = ShopItem(name=name, description=description, price=price, creator_id=current_user.id, images=images)
        db.session.add(new_item)
        db.session.commit()

        flash("Shop item created successfully!", "success")
        return redirect(url_for('shop.shop'))

    return render_template("shop/create_shop_item.html", form=form)

@shop_bp.route('/edit/<int:item_id>', methods=['GET', 'POST'])
@login_required
def edit_shop_item(item_id):
    """
    GET: Displays the form to edit an existing shop item.
    POST: Handles the update of an existing shop item.
    """
    item = ShopItem.query.get_or_404(item_id)

    form = ShopItemForm(obj=item)

    if form.validate_on_submit():
        item.name = form.name.data
        images = []
        for f in form.images.data:
            if f:
                filename = secure_filename(f.filename)
                f.save(f"{current_app.config['UPLOAD_FOLDER']}/{filename}")
                image = Image(filename=filename)
                db.session.add(image)
                images.append(image)

        item.images = images
        item.description = form.description.data  # We don't clean as we trust the admins to not XSS their own users.
        item.price = form.price.data
        db.session.commit()

        flash("Shop item updated successfully!", "success")
        return redirect(url_for('shop.shop'))

    return render_template("shop/edit_shop_item.html", form=form, item=item)

@shop_bp.route('/delete/<int:item_id>')
@login_required
def delete_shop_item(item_id):
    """
    GET: Deletes a shop item. (yes I know I should use DELETE but this is simpler for now)
    """
    item = ShopItem.query.get_or_404(item_id)

    db.session.delete(item)
    db.session.commit()

    flash("Shop item deleted successfully!", "success")
    return redirect(url_for('shop.shop'))

templates/shop/create_shop_item.html
{% extends "layout.html" %}
{% block title %}Create Shop Item{% endblock %}
{% block content %}

    
    <h1>Create Shop Item</h1>

    <form method="post" action="{{ url_for('shop.create_shop_item') }}" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="box-form-dark">
            {% include 'shop/partials/create_shop_form.html' %}
        </fieldset>
    </form>
    {{ ckeditor.load() }}
    {{ ckeditor.config(name='description') }}

{% endblock %}

templates/shop/edit_shop_item.html
{% extends "layout.html" %}
{% block title %}Editing item: {{ item.name }}{% endblock %}
{% block content %}

    
    <h1>Editing item: {{ item.name }}</h1>

    <form method="post" action="{{ url_for('shop.edit_shop_item', item_id=item.id) }}" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="box-form-dark">
            {% include 'shop/partials/create_shop_form.html' %}
        </fieldset>
    </form>
    {{ ckeditor.load() }}
    {{ ckeditor.config(name='description') }}

    <a href="{{ url_for('shop.delete_shop_item', item_id=item.id) }}" class="btn btn-danger"
       onclick="return confirm('Are you sure you want to delete this item?');">Delete Item</a>

{% endblock %}

templates/shop/shop.html
{% extends "layout.html" %}

{% block title %}Shop{% endblock %}

{% block content %}
    <div class="shop-title-container">
        <h1>Shop items</h1>
    </div>
    

    {% if current_user.is_authenticated %}
    <p>
      <a href="{{ url_for('shop.create_shop_item') }}" class="btn btn-primary">Add new item</a>
    </p>
    {% endif %}

    {% if items %}
        <div class="shop-tile-list">
            {% for row in items|batch(2) %}
            {% for item in row %}
            <div class="shop-item">
                <div class="shop-card">
                    {% if item.images %}
                    <img src="/files/{{ item.images[0].filename }}" alt="Preview image for {{ item.title }}">
                    {% else %}
                    <img src="/static/images/logo.png" alt="Default logo for news post">
                    {% endif %}
                    <div class= "item-info">
                        <h2>{{ item.name }} - {{ item.price | format_price }}</h2>
                        <p>{{ ((item.description | safe).split('\n')[0].split('&nbsp;')[0]).strip() | truncate(50, True, '...') }}</p>
                        <div class="item-footer">
                            <a href="{{ url_for('shop.shop_item', item_id=item.id) }}" class="shop-read-more-btn">Read more</a>
                            <span class="item-date">{{ item.created_at | format_datetime }}</span>
                        </div>
                    </div>
                </div>
            </div>
                
            
            {% endfor %}
            {% endfor %}
        </div> 

    {% else %}
        <p>No shop items available at the moment.</p>
    {% endif %}
{% endblock %}

templates/shop/shop_item.html
{% extends "layout.html" %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
    <div class="view-shop-container">
    <div class="view-shop-title">
        <h1 class="shop-title">{{ item.name }}</h1>
    </div>

    {% if current_user.is_authenticated %}
      <p class="shop-controls">
        <a href="{{ url_for('shop.edit_shop_item', item_id=item.id) }}">Edit this item</a>
        <a href="{{ url_for('shop.delete_shop_item', item_id=item.id) }}" onclick="return confirm('Are you sure you want to delete this item?');">Delete this item</a>
      </p>
    {% endif %}

    <div class="view-shop-content">
      <div class="view-shop-image">
        {% if item.images %}
          <div id="shopCarousel" class="carousel slide mb-3" data-bs-ride="carousel">
            <div class="shop-carousel-inner">
              {% for image in item.images %}
                <div class="carousel-item {% if loop.first %}active{% endif %}">
                  <img src="/files/{{ image.filename }}" class="shop-d-block w-100 h-auto" alt="Image for {{ item.title }}">
                </div>
              {% endfor %}
            </div>
            {% if item.images|length > 1 %}
              <button class="carousel-control-prev" type="button" data-bs-target="#shopCarousel" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#shopCarousel" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            {% endif %}
          </div>
        {% else %}
          <img src="/static/images/logo.png" class="default-shop-image" alt="Default logo for shop item">
        {% endif %}
      </div>

      <div class="view-item-text">
        <h3>Price {{ item.price | format_price}}</h3>
        <p>{{ item.description | safe }}</p>
        <p class="shop-credits" style="font-size: 0.75rem;">
          Published on {{ item.created_at | format_datetime }} by {{ item.creator.first_name }} {{ item.creator.last_name }}<br>
          {% if item.updated_at %}
            Last updated on {{ item.updated_at | format_datetime }}
          {% endif %}
        </p>
        <p>
          <a href="{{ url_for('shop.shop') }}">← Back to Shop</a>
        </p>
      </div>
    </div>
  </div>

{% endblock %}